/* Passwordless login client. The server must send and verify OTPs; this page never creates or stores OTPs. */
(function(){
  const apiBase=(window.AUTH_API_BASE||'/api/auth').replace(/\/$/,''); const emailStep=document.getElementById('email-step'); const otpStep=document.getElementById('otp-step'); const emailInput=document.getElementById('email'); const otpInput=document.getElementById('otp'); const status=document.getElementById('status'); const emailButton=document.getElementById('email-button'); const verifyButton=document.getElementById('verify-button'); const resendButton=document.getElementById('resend'); let email=''; let timer;
  function message(text,error){status.textContent=text;status.classList.toggle('error',Boolean(error))} function busy(button,state){button.disabled=state;button.textContent=state?'Please wait…':button.dataset.label}
  async function post(path,body){let response;try{response=await fetch(apiBase+path,{method:'POST',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify(body)})}catch(_){throw new Error('OTP service तक connection नहीं हो पाया। थोड़ी देर बाद फिर कोशिश करें।')}let data={};try{data=await response.json()}catch(_){}if(response.status===404||response.status===405)throw new Error('OTP service अभी इस website पर connect नहीं है। Admin को email-OTP backend जोड़ना होगा।');if(!response.ok)throw new Error(data.message||'OTP request पूरी नहीं हो सकी। Please try again.');return data}
  function countdown(){let seconds=30;resendButton.disabled=true;resendButton.textContent='Resend OTP in '+seconds+'s';clearInterval(timer);timer=setInterval(function(){seconds--;if(seconds<=0){clearInterval(timer);resendButton.disabled=false;resendButton.textContent='Resend OTP'}else resendButton.textContent='Resend OTP in '+seconds+'s'},1000)}
  emailButton.addEventListener('click',async function(){if(!emailInput.checkValidity()){emailInput.reportValidity();return}email=emailInput.value.trim().toLowerCase();busy(emailButton,true);message('OTP भेजा जा रहा है…');try{await post('/request-otp',{email});emailStep.classList.add('hidden');otpStep.classList.remove('hidden');otpInput.focus();countdown();message('OTP आपके email पर भेज दिया गया है।')}catch(error){message(error.message,true)}finally{busy(emailButton,false)}});
  verifyButton.addEventListener('click',async function(){if(!/^\d{6}$/.test(otpInput.value.trim())){message('6 digit OTP डालें।',true);return}busy(verifyButton,true);message('OTP verify हो रहा है…');try{const result=await post('/verify-otp',{email,otp:otpInput.value.trim()});message(result.redirect?'Email verified. Redirecting…':'Email verified successfully.');if(result.redirect)window.location.assign(result.redirect)}catch(error){message(error.message,true)}finally{busy(verifyButton,false)}});
  resendButton.addEventListener('click',function(){emailButton.click()}); document.getElementById('change-email').addEventListener('click',function(){otpStep.classList.add('hidden');emailStep.classList.remove('hidden');message('');emailInput.focus()});
})();
